paths:
  music_dir: Output/Music
  staging_dir: Output/Staging
  video_dir: Output/Music Videos
tidal:
  quality: HI_RES
  token: ''
  client_id: ''
  client_secret: ''
deezer:
  arl: ''
  quality: FLAC
youtube:
  cookies_path: ''
  token: ''
web_dl:
  audio_format: flac
  download_delay: 2
  video_format: mp4
ai:
  beam_size: 5
  device: auto
  model_size: medium
  precision: int8
  vad_filter: true
ui:
  theme: Dark
  search_results: 5
  fallback_enabled: true
  repair_config: false
formats:
  audio_format: flac
  video_format: mp4
  video_resolution: 1080p
  lyric_format: lrc
  subtitle_format: srt
